settings:

      - !com.mitc.dto.Settings

        timeout: 2
        encrypted: true
        key: Mary has one cat

        site: C:\PrivateWS\javafx-toc\site\
        theme: cupertino

        locale: en_US

        height: 650
        width: 450

        server: localhost
        port: 9876
