settings:
      - !com.mitc.util.Settings

        timeout: 2
        encrypted: true
        key: Mary has one cat

        site: C:\PrivateWS\javafx-toc\site\
        theme: cupertino

        locale: en_US
        level: trace

        height: 600
        width: 420
