settings:
      - !com.mitc.util.Settings

        site: C:\PrivateWS\applications\javafx-toc\site\
        theme: cupertino

        locale: nl_BE
        level: trace

        height: 600
        width: 420