!settings

  encrypted: true
  key: Mary has one cat

  # undecorated: false
  # theme: cupertino

  height: 680
  width: 500

  host: localhost
  # restPort: 9999
  # vertxPort: 8888
  # hawtioPort: 7777

  hawtio: false
  monitoring: true