!settings

  encrypted: true
  # key: test

  # theme: cupertino

  height: 700
  width: 500

  mode: bootstrap

  host: localhost
  # restPort: 9999
  # vertxPort: 8888
  # hawtioPort: 7777

  hawtio: false
  monitoring: false

  # proxyUser:
  # proxyPass:
  # proxyHost: 147.67.117.13
  # proxyPort: 8012