settings:

      - !com.mitc.util.Settings

        timeout: 2
        encrypted: true
        key: Mary has one cat

        theme: cupertino

        locale: en_US

        height: 680
        width: 500
